# Generated by Django 5.2.1 on 2025-11-01 22:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TvMazeAPIid', models.PositiveIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True)),
                ('premiered', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('TvMazeAPI_season_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('season_release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('season_episode_cnt', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='tvshows_app.tvshow')),
            ],
            options={
                'ordering': ['season_number'],
                'unique_together': {('show', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('TvMazeAPI_episode_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('episode_title', models.CharField(blank=True, max_length=255)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('episode_runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('season_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='tvshows_app.season')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('season_number', 'episode_number')},
            },
        ),
    ]
