# Generated by Django 5.2.1 on 2025-11-16 22:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShowRatingsAndReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('show', 'Show'), ('season', 'Season'), ('episode', 'Episode')], max_length=10)),
                ('couple_slug', models.SlugField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('review_justification', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvshow_reviews', to=settings.AUTH_USER_MODEL)),
                ('tv_episode_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tvshows_app.episode')),
                ('tv_season_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tvshows_app.season')),
                ('tv_show_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tvshows_app.tvshow')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('tv_show_type__isnull', False)), fields=('reviewer', 'tv_show_type'), name='unique_show_review_per_user'), models.UniqueConstraint(condition=models.Q(('tv_season_type__isnull', False)), fields=('reviewer', 'tv_season_type'), name='unique_season_review_per_user'), models.UniqueConstraint(condition=models.Q(('tv_episode_type__isnull', False)), fields=('reviewer', 'tv_episode_type'), name='unique_episode_review_per_user')],
            },
        ),
    ]
