# Generated by Django 5.2.1 on 2025-11-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows_app', '0002_tvshowratingsandreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='creators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='status',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
