# Generated by Django 5.2.1 on 2025-12-10 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows_app', '0003_tvshow_creators_tvshow_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshowratingsandreviews',
            old_name='review_justification',
            new_name='rating_justification',
        ),
        migrations.AlterField(
            model_name='tvshowratingsandreviews',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
