# Generated by Django 5.2.1 on 2026-01-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews_hub', '0003_add_tv_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='TMDB_Api_ID',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_yr',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(condition=models.Q(('TMDB_Api_ID__isnull', False)), fields=('TMDB_Api_ID',), name='unique_movie_tmdb_api_Id_not_null'),
        ),
        migrations.DeleteModel(
            name='TvShowModel',
        ),
        migrations.DeleteModel(
            name='TvShowSeason',
        ),
    ]
