# Generated by Django 5.2.1 on 2026-01-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews_hub', '0004_remove_tvshowseason_show_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
